### ISSUE TITLE
Nil assertion failed on get

### ISSUE THREAD

**Issue by asterite** [porras/crul#5]
Hola!

In the lastest version (the one with cookies) doing `crul http://httpbin.org/get?a=b` gives a nil assertion failed. The culprit is [this line](https://github.com/porras/crul/blob/master/src/command.cr#L8) and it's because if an URI doesn't have a port, it doesn't give you back a default one (like in Ruby), it gives you nil. Maybe we can fix this in the standard library. But for now I guess you'll have to do `@options.url.port || 80`.

Similarly, if you do `crul www.google.com` it gives a nil assertion failed because the host is nil. `URI.parse("www.google.com") gives you an URI with just a path, everything else is nil. I don't know if this is the correct behaviour, but I just checked and Ruby does the same. In this case, if there's no host you can try adding "http://" to the uri and parse it again :-)

**Comment by porras** [comment]
Ooops,

Thanks for the report, which I didn't read before because I was releasing 0.3.0 :shame:

I guess 0.3.1 is going out in some minutes :disappointed:
